export const ROLE_CODES = {
  MEMBER: 'MEMBER',
  EXECUTIVE_MEMBER: 'EXECUTIVE_MEMBER',
  BATCH_COORDINATOR: 'BATCH_COORDINATOR',
  BATCH_MENTOR: 'BATCH_MENTOR',
  FINANCE_MANAGER: 'FINANCE_MANAGER',
  PLATFORM_ADMIN: 'PLATFORM_ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN',
} as const;

export const ROLE_LABELS: Record<(typeof ROLE_CODES)[keyof typeof ROLE_CODES], string> = {
  [ROLE_CODES.MEMBER]: 'Member',
  [ROLE_CODES.EXECUTIVE_MEMBER]: 'Executive Member',
  [ROLE_CODES.BATCH_COORDINATOR]: 'Batch Coordinator',
  [ROLE_CODES.BATCH_MENTOR]: 'Batch Mentor',
  [ROLE_CODES.FINANCE_MANAGER]: 'Finance Manager',
  [ROLE_CODES.PLATFORM_ADMIN]: 'Platform Admin',
  [ROLE_CODES.SUPER_ADMIN]: 'Super Admin',
};

export const PERMISSION_CODES = {
  MEMBERSHIP_REGISTRATION_APPROVE: 'membership.registration.approve',
  MEMBERSHIP_REGISTRATION_APPROVE_BATCH: 'membership.registration.approve_batch',
  IAM_CATALOG_READ: 'iam.catalog.read',
  IAM_USER_ACCESS_READ: 'iam.user_access.read',
  IAM_ROLE_ASSIGNMENT_MANAGE_BATCH_ROLES: 'iam.role_assignment.manage_batch_roles',
  IAM_ROLE_ASSIGNMENT_MANAGE_FINANCE_MANAGER: 'iam.role_assignment.manage_finance_manager',
  IAM_ROLE_ASSIGNMENT_MANAGE_PLATFORM_ADMIN: 'iam.role_assignment.manage_platform_admin',
  IAM_ROLE_ASSIGNMENT_MANAGE_SUPER_ADMIN: 'iam.role_assignment.manage_super_admin',
  IAM_EXECUTIVE_POSITION_MANAGE: 'iam.executive_position.manage',
  IAM_EXECUTIVE_TERM_MANAGE: 'iam.executive_term.manage',
  IAM_AUDIT_READ_LIMITED: 'iam.audit.read_limited',
  IAM_AUDIT_READ_ALL: 'iam.audit.read_all',
  SYSTEM_FULL_ACCESS: 'system.full_access',
  SCHOLARSHIP_APPLICATION_CREATE: 'scholarship.application.create',
  SCHOLARSHIP_APPLICATION_READ_OWN: 'scholarship.application.read_own',
  SCHOLARSHIP_APPLICATION_UPDATE_OWN: 'scholarship.application.update_own',
  SCHOLARSHIP_APPLICATION_SUBMIT: 'scholarship.application.submit',
  SCHOLARSHIP_APPLICATION_READ_ASSIGNED: 'scholarship.application.read_assigned',
  SCHOLARSHIP_APPLICATION_READ_BATCH: 'scholarship.application.read_batch',
  SCHOLARSHIP_APPLICATION_READ_ALL: 'scholarship.application.read_all',
  SCHOLARSHIP_APPLICATION_REQUEST_INFO: 'scholarship.application.request_info',
  SCHOLARSHIP_APPLICATION_REJECT: 'scholarship.application.reject',
  SCHOLARSHIP_APPLICATION_APPROVE: 'scholarship.application.approve',
  SCHOLARSHIP_APPLICATION_REASSIGN: 'scholarship.application.reassign',
  SCHOLARSHIP_APPLICATION_MARK_WRONG_DISBURSEMENT: 'scholarship.application.mark_wrong_disbursement',
  SCHOLARSHIP_ALLOCATION_CREATE: 'scholarship.allocation.create',
  SCHOLARSHIP_ALLOCATION_READ_OWN: 'scholarship.allocation.read_own',
  SCHOLARSHIP_ALLOCATION_READ_ALL: 'scholarship.allocation.read_all',
  SCHOLARSHIP_ALLOCATION_CONFIRM: 'scholarship.allocation.confirm',
  SCHOLARSHIP_ALLOCATION_DISPUTE: 'scholarship.allocation.dispute',
  SCHOLARSHIP_ALLOCATION_RESOLVE_DISPUTE: 'scholarship.allocation.resolve_dispute',
  SCHOLARSHIP_TRANSACTION_CONFIRM_RECEIVED: 'scholarship.transaction.confirm_received',
  SCHOLARSHIP_TRANSACTION_REQUEST_FOLLOWUP: 'scholarship.transaction.request_followup',
  SCHOLARSHIP_TRANSACTION_READ_ASSIGNED: 'scholarship.transaction.read_assigned',
  SCHOLARSHIP_TRANSACTION_READ_MEMBER_REGISTER: 'scholarship.transaction.read_member_register',
  SCHOLARSHIP_PROOF_UPLOAD: 'scholarship.proof.upload',
  SCHOLARSHIP_PROOF_REVIEW: 'scholarship.proof.review',
  SCHOLARSHIP_REFUND_REQUEST: 'scholarship.refund.request',
  SCHOLARSHIP_REFUND_RESPOND: 'scholarship.refund.respond',
  SCHOLARSHIP_REFUND_MANAGE: 'scholarship.refund.manage',
  SCHOLARSHIP_REFUND_CONFIRM_RECEIVED: 'scholarship.refund.confirm_received',
  SCHOLARSHIP_DASHBOARD_READ_BATCH: 'scholarship.dashboard.read_batch',
  SCHOLARSHIP_DASHBOARD_READ_MENTOR: 'scholarship.dashboard.read_mentor',
  SCHOLARSHIP_DASHBOARD_READ_ORG: 'scholarship.dashboard.read_org',
  SCHOLARSHIP_FINANCIAL_DETAILS_READ: 'scholarship.financial_details.read',
  SCHOLARSHIP_SENSITIVE_DATA_READ: 'scholarship.sensitive_data.read',
  SCHOLARSHIP_AUDIT_READ: 'scholarship.audit.read',
  SCHOLARSHIP_OVERRIDE: 'scholarship.override',
} as const;
