import type { Icon } from '@phosphor-icons/react';
import {
  Image,
  LinkSimpleHorizontal,
  ListBullets,
  ListNumbers,
  Quotes,
  TextAa,
  TextAlignCenter,
  TextAlignJustify,
  TextAlignLeft,
  TextAlignRight,
  TextB,
  TextH,
  TextHFive,
  TextHFour,
  TextHOne,
  TextHSix,
  TextHThree,
  TextHTwo,
  TextIndent,
  TextItalic,
  TextOutdent,
  TextT,
  TextUnderline,
  YoutubeLogo,
} from '@phosphor-icons/react';

export const EDITOR_ICONS = {
  bold: TextB,
  underline: TextUnderline,
  italic: TextItalic,
  heading: TextH,
  font_family: TextT,
  font_size: TextAa,
  text_align_left: TextAlignLeft,
  text_align_right: TextAlignRight,
  text_align_center: TextAlignCenter,
  text_align_justify: TextAlignJustify,
  orderedList: ListNumbers,
  bulletList: ListBullets,
  link: LinkSimpleHorizontal,
  video: YoutubeLogo,
  image: Image,
  heading_1: TextHOne,
  heading_2: TextHTwo,
  heading_3: TextHThree,
  heading_4: TextHFour,
  heading_5: TextHFive,
  heading_6: TextHSix,
  indent_in: TextIndent,
  indent_out: TextOutdent,
  blockquote: Quotes,
} as Record<string, Icon>;

export const FONT_FAMILY_LIST = [
  {
    label: 'DM Sans',
    value: 'DM Sans',
  },
  {
    label: 'Mukta Hindi',
    value: 'Mukta',
  },
  // {
  //   label: 'Georgia',
  //   value: 'Georgia',
  // },
  // {
  //   label: 'Helvetica',
  //   value: 'Helvetica',
  // },
  // {
  //   label: 'Sans Serif',
  //   value: 'Sans Serif',
  // },
  // {
  //   label: 'Tahoma',
  //   value: 'Tahoma',
  // },
  // {
  //   label: 'Times New Roman',
  //   value: 'Times New Roman',
  // },
  // {
  //   label: 'Trebuchet',
  //   value: 'Trebuchet',
  // },
  // {
  //   label: 'Verdana',
  //   value: 'Verdana',
  // },
];
export const HEADINGS_LIST = [
  {
    label: 'Heading 1',
    icon: EDITOR_ICONS.heading_1,
    value: 1,
  },
  {
    label: 'Heading 2',
    icon: EDITOR_ICONS.heading_2,
    value: 2,
  },
  {
    label: 'Heading 3',
    icon: EDITOR_ICONS.heading_3,
    value: 3,
  },
  {
    label: 'Heading 4',
    icon: EDITOR_ICONS.heading_4,
    value: 4,
  },
  {
    label: 'Heading 5',
    icon: EDITOR_ICONS.heading_5,
    value: 5,
  },
  {
    label: 'Heading 6',
    icon: EDITOR_ICONS.heading_6,
    value: 6,
  },
];
export const FONT_SIZE_LIST = [
  '8px',
  '10px',
  '12px',
  '14px',
  '16px',
  '18px',
  '20px',
  '22px',
  '24px',
  '26px',
  '28px',
  '30px',
  '32px',
  '34px',
  '36px',
  '38px',
  '40px',
  '42px',
  '44px',
  '46px',
  '48px',
  '50px',
  '56px',
  '62px',
  '68px',
];
